export const COM_STATUS = 'COM_STATUS'
export const COM_SET_LEFT_MENU = 'COM_SET_LEFT_MENU'
export const COM_SET_ACTIVE_MENU = 'COM_SET_ACTIVE_MENU'

// HOME
export const HOME_SET_CENTER_APP_LIST = 'HOME_SET_CENTER_APP_LIST'
export const HOME_SET_LOCAL_APP_LIST = 'HOME_SET_LOCAL_APP_LIST'
